spring:
  application:
    name: notification-service
  config:
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true
  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}

app:
  email:
    from: ${APP_EMAIL_FROM:no-reply@mailhog.local}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,gateway