spring:
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: "configserver:http://host.docker.internal:8888"
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: true
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: maximumSize=500, expireAfterWrite=5m

  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}

app:
  email:
    from: ${APP_EMAIL_FROM:no-reply@mailhog.local}